apiVersion: v1
kind: Service
metadata:
  name: reverse-words
  labels:
    app: reverse-words
spec:
  type: NodePort
  selector:
    app: reverse-words
  ports:
    - name: http              # ВАЖНО: имя порта используется в ServiceMonitor
      port: 80                # порт внутри кластера
      targetPort: 8080        # порт контейнера
      nodePort: 30080         # внешний порт на узле minikube
      protocol: TCP
